
version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "40000:40000"  # Порт для отладки с помощью delve
      - "80:8080"  # Проброс порта 8080 из контейнера на порт 80 на хосте

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: