
version: '3'
services:
  app:
    build: .
    environment:
      - MONGO_URI=${MONGO_URI}
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=8081
      - LOCAL_MODE=false
    depends_on:
      - mongo
    ports:
      - "81:8081"
    networks:
      - app_network

  mongo:
    image: mongo:6.0.15
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge