version: '3'
services:
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - BOT_TOKEN=7012505888:AAEtQoe-AwaoNoC5OPUQaQ6jAqNHKYAKcQk
      - WEBHOOK_URL=https://tournament-bot.online/webhook
      - PORT=8081
      - LOCAL_MODE=false

    depends_on:
      - mongo
    ports:
      # - "40000:40000"  # Закомментируйте эту строку
      - "81:8081"  # Проброс порта 8081 из контейнера на порт 81 на хосте

  mongo:
    image: mongo:6.0.15
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
