version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      # - "40000:40000"  # Закомментируйте эту строку
      - "81:8081"  # Проброс порта 8081 из контейнера на порт 81 на хосте

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
