
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check directory and git status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            cd /root/bot/tournament-bot
            echo "Project directory: $(pwd)"
            echo "Directory contents:"
            ls -la
            echo "Git status:"
            git status

      - name: Pull latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bot/tournament-bot
            git pull origin main

      - name: Create .env file with secrets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: MONGO_ROOT_USERNAME,MONGO_ROOT_PASSWORD,MONGO_APP_USERNAME,MONGO_APP_PASSWORD,BOT_TOKEN,WEBHOOK_URL
          script: |
            cd /root/bot/tournament-bot
            cat > .env << EOL
            MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            MONGO_URI=mongodb://${{ secrets.MONGO_APP_USERNAME }}:${{ secrets.MONGO_APP_PASSWORD }}@mongo:27017/tournament?authSource=tournament
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}
            EOL

      - name: Build and start Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bot/tournament-bot
            echo "Building and starting containers:"
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            echo "Checking container status:"
            docker-compose ps
            echo "Application logs:"
            docker-compose logs app
