
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check directory and git status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            cd /root/bot/tournament-bot
            echo "Project directory: $(pwd)"
            echo "Directory contents:"
            ls -la
            echo "Git status:"
            git status

      - name: Pull latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bot/tournament-bot
            git pull origin main

      - name: Update Docker Compose file with secrets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: MONGO_ROOT_USERNAME,MONGO_ROOT_PASSWORD,MONGO_APP_USERNAME,MONGO_APP_PASSWORD
          script: |
            cd /root/bot/tournament-bot
            # Обновляем docker-compose.yml с секретами
            sed -i 's|MONGO_INITDB_ROOT_USERNAME=.*|MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}|g' docker-compose.yml
            sed -i 's|MONGO_INITDB_ROOT_PASSWORD=.*|MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}|g' docker-compose.yml
            sed -i 's|MONGO_URI=.*|MONGO_URI=mongodb://${{ secrets.MONGO_APP_USERNAME }}:${{ secrets.MONGO_APP_PASSWORD }}@mongo:27017/tournament?authSource=tournament|g' docker-compose.yml

      - name: Build and start Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bot/tournament-bot
            echo "Building and starting containers:"
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            echo "Checking container status:"
            docker-compose ps
            echo "Application logs:"
            docker-compose logs app